[package]
name = "btm"
version = "0.1.0"
authors = ["Jordan Danford <jordandanford@gmail.com>"]
edition = "2024"

[dependencies]
ternary = { version = "0.4", git = "https://github.com/jdanford/ternary", tag = "v0.4" }
