[package]
name = "btm"
version = "0.2.0"
authors = ["Jordan Danford <jordandanford@gmail.com>"]
edition = "2024"

[dependencies]
ternary = { version = "0.6", git = "https://github.com/jdanford/ternary", tag = "v0.6" }
